### ISSUE TITLE
Add support for MySqlConnector

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus.MySql#10]
We have moved over from the Oracle connector to the Open Source one that can be found here:

https://mysqlconnector.net/

Alas since the Rebus project is compiled specifically for the Oracle MySql, it does not work out of the box. If there are no objections I would like to either add conditional compilation to support the non-oracle connector so it can be published as a separate NuGet package, or just clone the project into a new Git project to maintain it separately.

What would be the preference? For now I will make a branch for this conversion in my fork of this repo.

**Comment by kendallb** [comment]
Almost done with porting the SQL Server version to MySqlConnector and I have a whole new code tree for it. When it's done, I would like to somehow get it into the official build process and up on NuGet?

**Comment by kendallb** [comment]
Ok, my port is done. All unit tests pass so it's a full clone of the SQL Server version. It could probably be used to back port to the Oracle connector to make that a full featured version also since the differences are minor. But for now I have it as a separate project and plan to push my own NuGet package until it gets accept upstream.

https://github.com/kendallb/Rebus.MySqlConnector

**Comment by mookid8000** [comment]
I've gone over your work – looks great! 🙂  Made one small fix to `MySqlTimeoutManager` that used `DateTimeOffset`s, which seems to be unsupported.

It's out as Rebus.MySql 3.0.0-b1 now 🎉
