### ISSUE TITLE
Not working with parallel processing

### ISSUE THREAD

**Issue by renemadsen** [rebus-org/Rebus.MySql#7]
When using this transport for some reason the transporter is not making Rebus do work in paralell.

See attatched project example.
[RebusTesting.zip](https://github.com/rebus-org/Rebus.MySql/files/3665260/RebusTesting.zip)

**Comment by mookid8000** [comment]
When you say that it doesn't work in parallel, what do you actually mean?

Do you get an error?

What are the symptoms?

**Comment by mookid8000** [comment]
Hi @renemadsen , I'm closing this issue for now. Please feel free to pick it up again, if you're still experiencing something weird.

**Comment by JonCanning** [comment]
I've just discovered this too. Created a simple pub/sub using MySql and processing is always sequential, but is parallel with SqlServer
`3.0.0-b5` works!
