### ISSUE TITLE
Update needed for Rebus 6.0.0?

### ISSUE THREAD

**Issue by sbmw** [rebus-org/Rebus.MySql#8]
Hi, I upgraded Rebus.ServiceProvider to v5.0.1 while Rebus.MySql is still at v1.1.2.

I'm now getting this error:

```
Exception has occurred: CLR/Rebus.Injection.ResolutionException
An exception of type 'Rebus.Injection.ResolutionException' occurred in Rebus.dll but was not handled in user code: 'Could not resolve Rebus.Subscriptions.ISubscriptionStorage with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.MissingMethodException : Method not found: 'System.Collections.Generic.HashSet`1<!!0> Rebus.Extensions.EnumerableExtensions.ToHashSet(System.Collections.Generic.IEnumerable`1<!!0>)'.
```

My setup is as follows:

```
services.AddRebus(configure => configure
    .Logging(l => l.Console(LogLevel.Warn))
    .Subscriptions(x => x.StoreInMySql(connectionString, "Subscriptions", true, true))
    .Transport(t => t.UseMySql(connectionString, "Transport", configuration["AppName"])));

services.AutoRegisterHandlersFromAssembly(assemblyName);
```

Do I need to update my setup or am I right in thinking this is a MySql package issue?

Thanks!
Matt

**Comment by mookid8000** [comment]
it's because code changes are required to make it compatible with Rebus 6.... stay tuned 🙂

**Comment by mookid8000** [comment]
Rebus.MySql 2.0.0 is on NuGet.org now! Thanks for reminding me to do this 😁

**Comment by sbmw** [comment]
Thank you so much for that amazingly fast update!  BUT unfortunately I still see the same error on updating to Rebus.MySql 2.0.0...  Is there anything I need to change in my config?

**Comment by sbmw** [comment]
The full error:

Exception has occurred: CLR/Rebus.Injection.ResolutionException
An exception of type 'Rebus.Injection.ResolutionException' occurred in Rebus.dll but was not handled in user code: 'Could not resolve Rebus.Subscriptions.ISubscriptionStorage with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.MissingMethodException : Method not found: 'System.Collections.Generic.HashSet`1<!!0> Rebus.Extensions.EnumerableExtensions.ToHashSet(System.Collections.Generic.IEnumerable`1<!!0>)'.
   at Rebus.MySql.Subscriptions.MySqlSubscriptionStorage.<EnsureTableIsCreated>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Rebus.MySql.Subscriptions.MySqlSubscriptionStorage.EnsureTableIsCreated()
   at Rebus.Config.MySqlConfigurationExtensions.<>c__DisplayClass0_0.<StoreInMySql>b__0(IResolutionContext c)
   at Rebus.Injection.Injectionist.Resolver`1.InvokeResolver(IResolutionContext context)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()

**Comment by mookid8000** [comment]
ah, damn! could you try Rebus.MySql 2.0.1 ?

**Comment by sbmw** [comment]
Sorry for the slow reply.  Yes, that works perfectly!  Thanks for the quick fix and the amazing product suite!
